version: '3'

networks:
  produto_net:
    driver: bridge

volumes:
  mongodb:
  movies:
  

services:
  mongo:
    image: mongo:4.4.3
    restart: always
    networks:
      - produto_net
    volumes:
      - mongodb:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopwd
  web:
    image: harrisonlima/rotten-potatoes:v1
    depends_on:
      - mongo
    ports:
      - 5000:5000
    networks:
      - produto_net
    volumes:
      - .:/app
  mongo-express:
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    networks:
      - produto_net
    volumes:
      - mongodb:/data/db
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongouser:mongopwd@mongo:27017/
  mongodb-exporter:
    image: harrisonlima/mongo_exporter
    ports:
      - 9216:9216
    networks:
      - produto_net
    depends_on:
      - mongo
    environment:
      MONGODB_URI: mongodb://mongouser:mongopwd@mongo:27017/
  prometheus:
    image: prom/prometheus:v2.22.0
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
      - ./alert-rules.yaml:/etc/prometheus/alert-rules.rules
    depends_on:
      - web
    networks:
      - produto_net
    ports:
      - 9090:9090
  grafana:
    image: grafana/grafana:8.5.15
    ports: 
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - produto_net
  alertmanager:
    image: prom/alertmanager:v0.21.0
    volumes:
      - ./alert-manager.yaml:/prometheus/alertmanager.yml
    command:
      - '--config.file=/prometheus/alertmanager.yml'
    ports:
      - 9093:9093
    networks:
      - produto_net
    depends_on:
      - prometheus

